package command

import (
	"context"
	"fmt"
	"os"
	"strings"

	"github.com/mohityadav8/cncf-lens/internal/cli"
)

// Completion builds the `lens completion` command.
func Completion() *cli.Command {
	return &cli.Command{
		Name:    "completion",
		Group:   "Setup",
		Summary: "Generate a shell completion script",
		Usage:   "lens completion <bash|zsh|fish>",
		Long: `Completion prints a shell completion script to stdout. Source it from your
shell profile, or drop it in your shell's completion directory.

bash:
  lens completion bash > /etc/bash_completion.d/lens

zsh:
  lens completion zsh > "${fpath[1]}/_lens"

fish:
  lens completion fish > ~/.config/fish/completions/lens.fish

To try it in the current shell without installing:
  source <(lens completion bash)`,
		Examples: []string{
			"lens completion bash > /etc/bash_completion.d/lens",
			"source <(lens completion zsh)",
		},
		Run: runCompletion,
	}
}

func runCompletion(_ context.Context, args []string) error {
	if len(args) != 1 {
		return fmt.Errorf("%w: specify one of bash, zsh, fish", cli.ErrUsage)
	}

	var script string
	switch strings.ToLower(args[0]) {
	case "bash":
		script = bashCompletion
	case "zsh":
		script = zshCompletion
	case "fish":
		script = fishCompletion
	default:
		return fmt.Errorf("%w: unsupported shell %q — use bash, zsh or fish",
			cli.ErrUsage, args[0])
	}

	_, err := fmt.Fprint(os.Stdout, script)
	return err
}

// The completion scripts are generated by hand rather than derived from the
// flag set at runtime. Deriving them would keep them automatically in sync, but
// it would also mean every completion keystroke shells out to the binary, which
// is noticeably slow. These lists are short and change rarely; CI catches drift
// via TestCompletionListsEveryCommand.

const commandList = "audit completion cost diagnose doctor init trace watch help version"

const globalFlagList = "--config --context --namespace --pod --workload --since " +
	"--output --no-color --no-cache --verbose --only --skip --timeout --limit --help"

const bashCompletion = `# bash completion for lens
_lens_completions() {
    local cur prev commands global_flags
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    commands="` + commandList + `"
    global_flags="` + globalFlagList + `"

    # Values for flags that take a fixed set of options.
    case "${prev}" in
        --output)
            COMPREPLY=( $(compgen -W "terminal json sarif markdown" -- "${cur}") )
            return 0
            ;;
        --since|--lookback|--timeout|--interval)
            COMPREPLY=( $(compgen -W "5m 15m 30m 1h 6h 24h" -- "${cur}") )
            return 0
            ;;
        --min-severity|--fail-on)
            COMPREPLY=( $(compgen -W "debug info warning error critical" -- "${cur}") )
            return 0
            ;;
        --namespace)
            # Offer live namespaces when kubectl is available.
            if command -v kubectl >/dev/null 2>&1; then
                COMPREPLY=( $(compgen -W "$(kubectl get ns -o name 2>/dev/null | cut -d/ -f2)" -- "${cur}") )
            fi
            return 0
            ;;
        --only|--skip)
            COMPREPLY=( $(compgen -W "kubernetes prometheus loki jaeger falco" -- "${cur}") )
            return 0
            ;;
        completion)
            COMPREPLY=( $(compgen -W "bash zsh fish" -- "${cur}") )
            return 0
            ;;
        help)
            COMPREPLY=( $(compgen -W "${commands}" -- "${cur}") )
            return 0
            ;;
    esac

    if [[ ${cur} == -* ]] ; then
        local cmd_flags=""
        case "${COMP_WORDS[1]}" in
            diagnose) cmd_flags="--metric --lookback --max-causes --min-score" ;;
            trace)    cmd_flags="--id --correlate" ;;
            watch)    cmd_flags="--interval --min-severity" ;;
            audit)    cmd_flags="--min-severity --fail-on" ;;
            cost)     cmd_flags="--cpu-hour --gb-hour --top" ;;
            init)     cmd_flags="--force --output-file" ;;
        esac
        COMPREPLY=( $(compgen -W "${global_flags} ${cmd_flags}" -- "${cur}") )
        return 0
    fi

    if [[ ${COMP_CWORD} -eq 1 ]] ; then
        COMPREPLY=( $(compgen -W "${commands}" -- "${cur}") )
        return 0
    fi
}
complete -F _lens_completions lens
`

const zshCompletion = `#compdef lens
# zsh completion for lens

_lens() {
    local -a commands
    commands=(
        'diagnose:Find the likely root cause of an anomaly'
        'trace:Follow one request across spans, logs, metrics and events'
        'watch:Stream correlated signals live from every backend'
        'audit:Report security-relevant findings across the stack'
        'cost:Estimate resource waste from actual versus requested usage'
        'doctor:Check that every configured backend is reachable'
        'init:Generate a starter config file'
        'completion:Generate a shell completion script'
        'help:Show help for a command'
        'version:Print the version'
    )

    _arguments -C \
        '1: :->cmd' \
        '*: :->args'

    case $state in
        cmd)
            _describe -t commands 'lens command' commands
            ;;
        args)
            case $words[2] in
                completion)
                    _values 'shell' bash zsh fish
                    ;;
                help)
                    _describe -t commands 'command' commands
                    ;;
                *)
                    _arguments \
                        '--config[path to config file]:file:_files' \
                        '--context[context to query]:context:' \
                        '--namespace[Kubernetes namespace]:namespace:' \
                        '--pod[pod name]:pod:' \
                        '--workload[workload or service name]:workload:' \
                        '--since[how far back to look]:duration:(5m 15m 30m 1h 6h 24h)' \
                        '--output[output format]:format:(terminal json sarif markdown)' \
                        '--only[backends to query exclusively]:backend:(kubernetes prometheus loki jaeger falco)' \
                        '--skip[backends to skip]:backend:(kubernetes prometheus loki jaeger falco)' \
                        '--timeout[per-backend timeout]:duration:' \
                        '--limit[max signals per backend]:number:' \
                        '--no-color[disable coloured output]' \
                        '--no-cache[bypass the local cache]' \
                        '--verbose[show all signals]'
                    ;;
            esac
            ;;
    esac
}

_lens "$@"
`

const fishCompletion = `# fish completion for lens

complete -c lens -f

complete -c lens -n __fish_use_subcommand -a diagnose   -d 'Find the likely root cause of an anomaly'
complete -c lens -n __fish_use_subcommand -a trace      -d 'Follow one request across spans, logs, metrics and events'
complete -c lens -n __fish_use_subcommand -a watch      -d 'Stream correlated signals live from every backend'
complete -c lens -n __fish_use_subcommand -a audit      -d 'Report security-relevant findings across the stack'
complete -c lens -n __fish_use_subcommand -a cost       -d 'Estimate resource waste from usage'
complete -c lens -n __fish_use_subcommand -a doctor     -d 'Check that every configured backend is reachable'
complete -c lens -n __fish_use_subcommand -a init       -d 'Generate a starter config file'
complete -c lens -n __fish_use_subcommand -a completion -d 'Generate a shell completion script'

complete -c lens -n '__fish_seen_subcommand_from completion' -a 'bash zsh fish'

complete -c lens -l config    -r -d 'path to config file'
complete -c lens -l context   -r -d 'context (cluster) to query'
complete -c lens -l namespace -r -d 'Kubernetes namespace'
complete -c lens -l pod       -r -d 'pod name'
complete -c lens -l workload  -r -d 'workload or service name'
complete -c lens -l since     -r -d 'how far back to look' -a '5m 15m 30m 1h 6h 24h'
complete -c lens -l output    -r -d 'output format' -a 'terminal json sarif markdown'
complete -c lens -l only      -r -d 'backends to query exclusively' -a 'kubernetes prometheus loki jaeger falco'
complete -c lens -l skip      -r -d 'backends to skip' -a 'kubernetes prometheus loki jaeger falco'
complete -c lens -l timeout   -r -d 'per-backend timeout'
complete -c lens -l limit     -r -d 'max signals per backend'
complete -c lens -l no-color     -d 'disable coloured output'
complete -c lens -l no-cache     -d 'bypass the local cache'
complete -c lens -l verbose      -d 'show all signals'

complete -c lens -n '__fish_seen_subcommand_from diagnose' -l metric     -r -d 'PromQL expression'
complete -c lens -n '__fish_seen_subcommand_from diagnose' -l lookback   -r -d 'causal search window'
complete -c lens -n '__fish_seen_subcommand_from diagnose' -l max-causes -r -d 'maximum hypotheses'
complete -c lens -n '__fish_seen_subcommand_from diagnose' -l min-score  -r -d 'minimum score'
complete -c lens -n '__fish_seen_subcommand_from trace'    -l id         -r -d 'trace ID to follow'
complete -c lens -n '__fish_seen_subcommand_from watch'    -l interval   -r -d 'poll interval'
complete -c lens -n '__fish_seen_subcommand_from audit'    -l fail-on    -r -d 'exit non-zero at this severity' -a 'warning error critical'
complete -c lens -n '__fish_seen_subcommand_from cost'     -l top        -r -d 'how many workloads to list'
`
